export const SUBGRAPH_URL =
  "https://api.studio.thegraph.com/query/73364/heartly-base-sepolia/version/latest";
export const CONTRACT_ADDRESS = "0x3D8B5AAC5723769ba3FF7888944540158a1B1E08";
// export const USDC_ADDRESS = "0x9c0110672FB855548Ec28a7ae18346D015C511E1";
export const USDC_ADDRESS = "0x5E9F5C4918E9eB31755bb84F9AAE126398c10A7A";
export const CONTRACT_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_usdcAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "BalanceWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "callId",
        type: "bytes32",
      },
    ],
    name: "CallCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "callId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "expert",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rating",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "flag",
        type: "bool",
      },
    ],
    name: "CallEnded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "callId",
        type: "bytes32",
      },
    ],
    name: "CallHold",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "callId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "expert",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum Heartly.CallType",
        name: "callType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "stakedAmount",
        type: "uint256",
      },
    ],
    name: "CallScheduled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "callId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "expert",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
    ],
    name: "CallStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Deposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ExpertBalanceWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "expert",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "voiceRate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "videoRate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "cid",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "expertise",
        type: "string",
      },
    ],
    name: "ExpertRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PlatformBalanceWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isVoice",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "updatedRate",
        type: "uint256",
      },
    ],
    name: "updatedExpertrates",
    type: "event",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_callId", type: "bytes32" }],
    name: "callHold",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "calls",
    outputs: [
      { internalType: "bytes32", name: "callId", type: "bytes32" },
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "expert", type: "address" },
      {
        internalType: "enum Heartly.CallType",
        name: "callType",
        type: "uint8",
      },
      {
        internalType: "enum Heartly.CallStatus",
        name: "status",
        type: "uint8",
      },
      { internalType: "uint256", name: "stakedAmount", type: "uint256" },
      { internalType: "uint256", name: "startTime", type: "uint256" },
      { internalType: "uint256", name: "endTime", type: "uint256" },
      { internalType: "uint256", name: "scheduledAt", type: "uint256" },
      { internalType: "uint256", name: "rating", type: "uint256" },
      { internalType: "uint256", name: "flagged", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_callId", type: "bytes32" }],
    name: "cancelCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_callId", type: "bytes32" },
      { internalType: "uint256", name: "_rating", type: "uint256" },
      { internalType: "bool", name: "flag", type: "bool" },
    ],
    name: "endCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "expertCalls",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "expertWithdrawBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "experts",
    outputs: [
      {
        internalType: "address payable",
        name: "walletAddress",
        type: "address",
      },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "expertise", type: "string" },
      { internalType: "uint256", name: "balance", type: "uint256" },
      {
        internalType: "uint256",
        name: "voiceRatePerMinute",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "videoRatePerMinute",
        type: "uint256",
      },
      { internalType: "string", name: "cid", type: "string" },
      { internalType: "bool", name: "isRegistered", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "getAvailableBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_callId", type: "bytes32" }],
    name: "getCallDetails",
    outputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "expert", type: "address" },
      {
        internalType: "enum Heartly.CallType",
        name: "callType",
        type: "uint8",
      },
      {
        internalType: "enum Heartly.CallStatus",
        name: "status",
        type: "uint8",
      },
      { internalType: "uint256", name: "stakedAmount", type: "uint256" },
      { internalType: "uint256", name: "startTime", type: "uint256" },
      { internalType: "uint256", name: "endTime", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_expert", type: "address" }],
    name: "getExpertCalls",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_expert", type: "address" }],
    name: "getExpertDetails",
    outputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "expertise", type: "string" },
      { internalType: "uint256", name: "balance", type: "uint256" },
      {
        internalType: "uint256",
        name: "voiceRatePerMinute",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "videoRatePerMinute",
        type: "uint256",
      },
      { internalType: "bool", name: "isRegistered", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_expert", type: "address" },
      {
        internalType: "enum Heartly.CallType",
        name: "_callType",
        type: "uint8",
      },
    ],
    name: "getExpertRate",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "getUserCalls",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "platformFeeWithdrawl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "string", name: "_expertise", type: "string" },
      {
        internalType: "uint256",
        name: "_voiceRatePerMinute",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_videoRatePerMinute",
        type: "uint256",
      },
      { internalType: "string", name: "_cid", type: "string" },
    ],
    name: "registerExpert",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_expert", type: "address" },
      {
        internalType: "enum Heartly.CallType",
        name: "_callType",
        type: "uint8",
      },
    ],
    name: "scheduleCall",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_callId", type: "bytes32" }],
    name: "startCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "expertAddress", type: "address" },
      { internalType: "bool", name: "isVoice", type: "bool" },
      { internalType: "uint256", name: "updatedRate", type: "uint256" },
    ],
    name: "updateCallRates",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdc",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userBalances",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userCalls",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "withdrawBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
