export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const REMOVE_LOGGED_USER = "REMOVE_LOGGED_USER";
export const SET_LOGGED_USER_DATA = "SET_LOGGED_USER_DATA";
export const RELOAD_PROFILE_DATA = "RELOAD_PROFILE_DATA";
export const PROFILE_RELOAD = "PROFILE_RELOAD";
export const GAME_FILTERS = "GAME_FILTERS";
export const USER_LAZY_POINT_UPDATE = "GAME_FILTERSUSER_LAZY_POINT_UPDATE";